# Generated by Django 4.1 on 2022-08-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='cretaed_by',
            new_name='created_by',
        ),
    ]
